#!/usr/bin/env bash
#
# bootstrap.sh — set up this machine from the dotfiles repo.
# Idempotent and fail-tolerant. Locates the repo via its own path, so run from anywhere:
#
#   ./bootstrap.sh            # run all steps for the current OS
#   ./bootstrap.sh --dry-run  # only show what dotman would place, then stop
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
cd "$REPO"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

log() { printf '\n==> %s\n' "$*"; }

# ------------------------------------------------------------------ macOS ---
bootstrap_macos() {
  command -v brew >/dev/null || { echo "Homebrew required first: https://brew.sh"; exit 1; }

  log "Place dotfiles (dotman)"
  if $DRY_RUN; then ./dotman.sh -i --dry-run; log "dry-run: stopping before real changes"; return; fi
  ./dotman.sh -i --force

  log "Install packages (brew bundle)"
  brew bundle --file="$REPO/Brewfile" || log "brew bundle had failures (review above)"
  brew bundle check --file="$REPO/Brewfile" || true

  log "Install runtimes (mise) + JS/Python toolchains"
  if command -v mise >/dev/null; then
    mise install || true
    mise exec -- corepack enable pnpm 2>/dev/null || true   # pnpm via node (corepack)
  fi
  if command -v uv      >/dev/null; then uv python install || true; fi
  if command -v git-lfs >/dev/null; then git lfs install   || true; fi
  if command -v tldr    >/dev/null; then tldr --update      || true; fi

  log "FileVault status (enable it — on-disk SSH keys depend on it)"
  fdesetup status || true

  # Login shell: staying on the system zsh by default. To switch to Homebrew zsh:
  #   sudo sh -c "echo $(brew --prefix)/bin/zsh >> /etc/shells" && chsh -s "$(brew --prefix)/bin/zsh"

  log "Done. Open a new shell to load the config."
}

# ------------------------------------------------------------------ Linux ---
bootstrap_linux() {
  log "Install base packages (apt)"
  sudo apt-get update
  # word-splitting is intentional: each package name becomes a separate argument
  # shellcheck disable=SC2046
  sudo apt-get install -y $(grep -vE '^\s*#|^\s*$' linux/apt-packages.txt)

  log "Place dotfiles (dotman)"
  if $DRY_RUN; then ./dotman.sh -i --dry-run; log "dry-run: stopping before real changes"; return; fi
  ./dotman.sh -i --force

  log "Install mise (official installer)"
  command -v mise >/dev/null || curl -fsSL https://mise.run | sh
  export PATH="$HOME/.local/bin:$PATH"

  log "Install runtimes + reference CLIs + gh/ghq (mise) + JS toolchain (corepack)"
  # Reference + single-use CLIs that are Homebrew formulae on macOS come from mise
  # on Linux. Write them to a machine-local conf.d layer, NOT the committed global
  # config.toml — dotman symlinks that into ~/.config/mise/, so `mise use -g` would
  # write through the symlink and dirty the repo. mise merges conf.d/*.toml with
  # config.toml automatically; node stays pinned in the committed config.toml.
  mkdir -p ~/.config/mise/conf.d
  cat > ~/.config/mise/conf.d/linux.toml <<'EOF'
# Machine-local (Linux), generated by bootstrap.sh — NOT tracked in the repo.
# Reference + single-use CLIs that live in Homebrew on macOS.
[tools]
eza = "latest"
bat = "latest"
fd = "latest"
ripgrep = "latest"
fzf = "latest"
starship = "latest"
zoxide = "latest"
delta = "latest"
gh = "latest"
ghq = "latest"
lazygit = "latest"
sd = "latest"
taplo = "latest"
"aqua:dbrgn/tealdeer" = "latest"   # tealdeer has no mise short-name; use the full aqua id (not tlrc, a different tldr client)
EOF
  mise install || true
  mise exec -- corepack enable pnpm 2>/dev/null || true

  log "Install uv (official installer) + Python toolchain"
  # uv: mac=brew (Brewfile); Linux=official installer → ~/.local/bin (already on PATH).
  command -v uv >/dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
  uv python install || true

  log "Install zsh plugins + xdg-ninja (git clone)"
  # Not in default apt and not in the mise registry (or we want to source them
  # directly): clone into ~/.local/share on Linux. macOS gets these from brew.
  # Idempotent: fast-forward pull if already cloned, else shallow clone.
  clone_or_pull() {  # $1 = repo (owner/name), $2 = destination dir
    if [ -d "$2/.git" ]; then git -C "$2" pull --ff-only --quiet || true
    else git clone --depth=1 --quiet "https://github.com/$1.git" "$2" || true
    fi
  }
  for _repo in zsh-users/zsh-autosuggestions \
               zsh-users/zsh-syntax-highlighting \
               zsh-users/zsh-history-substring-search; do
    clone_or_pull "$_repo" "$HOME/.local/share/zsh/${_repo#*/}"
  done
  clone_or_pull b3nj5m1n/xdg-ninja "$HOME/.local/share/xdg-ninja"
  # Wrapper (not a symlink) so xdg-ninja.sh resolves $0 to its real dir for its data.
  mkdir -p "$HOME/.local/bin"
  printf '#!/bin/sh\nexec "%s/.local/share/xdg-ninja/xdg-ninja.sh" "$@"\n' "$HOME" \
    > "$HOME/.local/bin/xdg-ninja" && chmod +x "$HOME/.local/bin/xdg-ninja"

  log "Set login shell to zsh"
  # Idempotent: only chsh when zsh exists and isn't already the login shell. Uses sudo (root
  # chsh needs no password re-prompt) — consistent with the apt steps above.
  _user="$(id -un)"
  _zsh="$(command -v zsh || true)"
  if [[ -z "$_zsh" ]]; then
    log "zsh not found; skipping chsh"
  elif [[ "$(getent passwd "$_user" | cut -d: -f7)" == "$_zsh" ]]; then
    :  # already the login shell
  elif sudo chsh -s "$_zsh" "$_user"; then
    log "Login shell set to $_zsh (log out and back in to take effect)"
  else
    log "Couldn't change login shell; run: chsh -s $_zsh"
  fi
  unset _user _zsh

  # WSL2 only: keep WSL's PATH clean by stopping the Windows PATH from bleeding in. Safe now
  # that the clipboard bridges use absolute paths (aliases.zsh). Gate on $WSL_DISTRO_NAME (a
  # real WSL distro) so it never fires inside a DevContainer on the WSL2 kernel. Idempotent.
  if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
    if grep -qs 'appendWindowsPath' /etc/wsl.conf; then
      :  # already configured — leave the existing setting alone
    elif grep -qs '\[interop\]' /etc/wsl.conf; then
      log "WSL2: /etc/wsl.conf already has [interop]; add 'appendWindowsPath=false' under it, then 'wsl --shutdown' from Windows."
    elif printf '\n[interop]\nappendWindowsPath=false\n' | sudo tee -a /etc/wsl.conf >/dev/null; then
      log "WSL2: set appendWindowsPath=false in /etc/wsl.conf — run 'wsl --shutdown' from Windows to apply."
    else
      log "WSL2: couldn't write /etc/wsl.conf (skipped); set appendWindowsPath=false by hand for a clean PATH."
    fi
  fi

  log "Done. Open a new shell to load the config."
}

case "$OSTYPE" in
  darwin*) bootstrap_macos ;;
  linux*)  bootstrap_linux ;;
  *) echo "Unsupported OS: $OSTYPE"; exit 1 ;;
esac
